version: '3'
services:
  Redis:
    image: "redis:5.0-rc"
    container_name: redis
    command: /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    ports:
      - "127.0.0.1:6379:6379"
    privileged: true
    restart: always